# suggestions_db.py
ENHANCED_SUGGESTIONS_DB_EN = [
    # Main Sections
    ("What is ARENA2036 about?", 0.95),
    ("What is the data protection policy at ARENA2036?", 0.8),
    ("How can I learn about the ARENA2036 project?", 0.9),
    ("Where can I find the ARENA2036 newsroom?", 0.8),
    ("What does ARENA2036 offer for me?", 0.8),
    ("What is about:tomorrow at ARENA2036?", 0.8),

    # Events
    ("What past events has ARENA2036 hosted?", 0.85),
    ("What upcoming events are at ARENA2036?", 0.9),
    ("What was the Fifth Eclipse Tractus-X Community Days?", 0.8),
    ("What is the Women Of Tech Conference 25'?", 0.8),
    ("What was the Fourth Eclipse Tractus-X Community Days?", 0.8),
    ("What was the Quantum-Day?", 0.8),
    ("What was the Third Eclipse Tractus-X Community Days?", 0.8),
    ("What was the Second Eclipse Tractus-X Community Days?", 0.8),
    ("What was SILS Forum: Presentation of DIN 72036?", 0.8),
    ("What was the Kick-off event KIRR Real?", 0.8),
    ("What is Hannover Messe 2025?", 0.8),
    ("What is 'the day after tomorrow - Open Research Campus'?", 0.8),
    ("What was the Results meeting - AAS4WH?", 0.8),
    ("What is 'Open source in Manufacturing-X projects'?", 0.8),
    ("What was Catena-X Release Day?", 0.8),
    ("What was the Theme day 'AI / Robotics'?", 0.8),
    ("What are the design guidelines for automating the wiring harness?", 0.8),
    ("What was the First Eclipse Tractus-X Community Days?", 0.8),
    ("What was the Transformation hub Wire Harness introduction?", 0.8),
    ("What was the Conference event AAS4WH?", 0.8),
    ("What were the Project status days in November 2019?", 0.8),
    ("What was the Innovation Forum Wire Harness 2025?", 0.8),
    ("What is WirePro Expo 2024?", 0.8),
    ("What was SynergyRegion Project completion & networking?", 0.8),
    ("What was Manufacturing-X: Milestone Meeting III?", 0.8),
    ("What was ARENA2036 - Review of the year 2024?", 0.8),
    ("What is DIN 72036 now available in English?", 0.8),
    ("What was the 'Intralogistics' theme day?", 0.8),
    ("What was the Design Factory Stuttgart Summer Gala 2023?", 0.8),
    ("What is THE Aerospace LÄND?", 0.8),
    ("What was the Design Factory Stuttgart Winter Gala 2023?", 0.8),
    ("What was DigiTain project start?", 0.8),
    ("What was Design Factory end-of-semester gala on June 23?", 0.8),
    ("What was WHAT THE HECK? - Hackathon 2022?", 0.8),
    ("What was Additive 2022 theme day?", 0.8),
    ("What was International Design Factory Week and DFGN.R Conference?", 0.8),
    ("What was Robo Handling Wire Harness?", 0.8),
    ("What was Stuttgart Conference on Automotive Production 2022?", 0.8),
    ("What was Science Minister Petra Olschowski's visit?", 0.8),
    ("What was Federal Minister for Economic Affairs and Energy Peter Altmaier's visit?", 0.8),
    ("What was Hannover Messe 2022?", 0.8),
    ("What was Design Factory first anniversary?", 0.8),
    ("What was Review of the Design Factory?", 0.8),
    ("What was ARENA2036 at the Hannover Messe 2025?", 0.8),
    ("What was Review 2024?", 0.8),
    ("What is Ü:MO 2026?", 0.8),
    ("What is Ü:MO 2025 - about the future of tomorrow?", 0.8),
    ("What was that was about:tomorrow 2024?", 0.8),
    ("What is Ü:MO 2025 - Partner day at the research campus?", 0.8),
    ("What was October 22, 2024: Opening Immersive Participation Lab Fraunhofer IAO?", 0.8),
    ("What was January 9, 2025: Visit to the Siemens equipment plant in Erlangen?", 0.8),
    ("What was February 19, 2025: Asset Administration Shell?", 0.8),
    ("What was February 25-26: Industrial Metaverse Conference 2025?", 0.8),
    ("What was March 31 - April 4, 2025: Hannover Messe 2025?", 0.8),
    ("What was May 8, 2025: Virtual worlds - experiencing opportunities in the metaverse?", 0.8),
    ("What was May 14 Women Of Tech Conference 2025?", 0.8),
    ("What was June 26, 2025: Ü:MO 2025 - Annual conference at the research campus?", 0.8),
    ("What was July 17, 2025: Transformation Summit 2025?", 0.8),
    ("What was October 02, 2025: Virtual process design with digital twins using the example of a robot system?", 0.8),
    ("What was October 30, 2025: Virtual Deep Dive: Digital Twin of a building?", 0.8),

    # Projects and Research
    ("What is Asset Administration Shell?", 0.9),
    ("What is Industrial-AI?", 0.9),
    ("What is Wire Harness", 0.9),
    ("What is the research focus at ARENA2036?", 0.9),
    ("What is the added value for ARENA2036 members?", 0.8),
    ("Who are the members of ARENA2036?", 0.8),
    ("What is the Transformation hub for the Wire Harness?", 0.8),
    ("What is the Wire Harness standardization initiative?", 0.8),
    ("What is the Interactive Bosch floor?", 0.8),
    ("What is the Industrial Metaverse?", 0.8),
    ("What is the project overview at ARENA2036?", 0.8),
    ("What is Catena-X?", 0.8),
    ("What is Network infrastructure for Industry 4.0?", 0.8),
    ("What is Connect4HCA ?", 0.8),
    ("What is EcoFrame ?", 0.8),
    ("What is CARpulse ?", 0.8),
    ("What is Well-defined ?", 0.8),
    ("Where can I find an overview of projects at ARENA2036?", 0.8),
    ("What is the project structure at ARENA2036?", 0.8),
    ("What is UpFilT?", 0.8),
    ("What is SynergyRegion?", 0.8),
    ("What is SDM4FZI?", 0.8),
    ("What is ProdUXion?", 0.8),
    ("What is PRIMA?", 0.8),
    ("What is PAIRS?", 0.8),
    ("What is InterSpiN?", 0.8),
    ("What is Science and support at ARENA2036?", 0.8),
    ("What are events of the IILS?", 0.8),
    ("What is Sustainability at ARENA2036?", 0.8),
    ("What is End-to-end digitalization?", 0.8),
    ("What is Digital product description?", 0.8),
    ("What is Logistics processes?", 0.8),
    ("What is Automated installation of the wiring harness in the vehicle?", 0.8),
    ("What is Production process and resources?", 0.8),
    ("What is Automation of quality inspection?", 0.8),
    ("What is Automation index?", 0.8),
    ("What is Concepts Wire Harness?", 0.8),
    ("What is Design rules for connectors?", 0.8),
    ("What is Design rules for the automation of the wiring harness?", 0.8),
    ("What is DIN standard?", 0.8),
    ("What is Creation of the IILS?", 0.8),
    ("What is Wire Harness innovation initiative?", 0.8),
    ("What is IC4F?", 0.8),
    ("What is I4Production?", 0.8),
    ("What is GrantSLAM?", 0.8),
    ("What is EINST4INE?", 0.8),
    ("What is Torque?", 0.8),
    ("What is DIRECT?", 0.8),
    ("What is Automated 3D printing system?", 0.8),
    ("What is About the team at ARENA2036?", 0.8),
    ("What is CreatorBOX?", 0.8),
    ("What is ARENA2036 Face Shields?", 0.8),
    ("What is ANTS4.0?", 0.8),
    ("What is AIMM?", 0.8),
    ("What is Fluid production?", 0.8),
    ("What is FlexCAR?", 0.8),
    ("What is Digital fingerprint?", 0.8),
    ("What is Agile innovation hub?", 0.8),
    ("What is KHoch3?", 0.8),
    ("What is UX for production?", 0.8),
    ("What is LeiFu?", 0.8),
    ("What is ForschFab?", 0.8),
    ("What is DigitPro?", 0.8),
    ("What is General information at ARENA2036?", 0.8),
    ("What is 5G MIPS?", 0.8),
    ("What is Transfer-X?", 0.8),
    ("What is Robotic SEAM?", 0.8),
    ("What is Opti-feel?", 0.8),
    ("What is KIRR Real?", 0.8),
    ("What is KI-D @ ARENA2036-X?", 0.8),
    ("What is HyMatFlow?", 0.8),
    ("What is Holodeck?", 0.8),
    ("What is High Speed Sintering?", 0.8),
    ("What is ECOPOWERBRAKE?", 0.8),
    ("What is DigiAutoFab?", 0.8),
    ("What is Design Factory Stuttgart?", 0.8),
    ("What is DARKO?", 0.8),
    ("What is Construct-X?", 0.8),
    ("What is CHEMampere?", 0.8),
    ("What is CeSaRa?", 0.8),
    ("What is CARS 2.0?", 0.8),
    ("What is AI-MATTERS?", 0.8),

    # Partners and Members
    ("What is OMRON's membership in ARENA2036?", 0.8),
    ("What is AMPLINK joining ARENA2036?", 0.8),
    ("What is ARENA2036's cooperation with acatech?", 0.8),
    ("What is new member SAFELOG?", 0.8),
    ("What is the new logo for ARENA2036?", 0.8),
    ("What is Bordnetze Digital 2024 in Stuttgart?", 0.8),
    ("What is new member QuiX Quantum?", 0.8),
    ("What is new partner Hahn-Schickard?", 0.8),
    ("What is new partner Schaeffler?", 0.8),
    ("What is new partner InstaWerk?", 0.8),
    ("What is new partner CIKONI?", 0.8),
    ("What is Agile Robots becoming a member of ARENA2036?", 0.8),
    ("What is ARENA2036 successfully entering Phase III?", 0.8),
    ("What is new member Gründermotor?", 0.8),
    ("What is new acatech member?", 0.8),
    ("What is new member Waveye?", 0.8),
    ("What is new member Precitec?", 0.8),
    ("What is DigiTain?", 0.8),
    ("What is Antitrust approval of the cooperation to automate the wire harness?", 0.8),
    ("What is ARENA2036-Wasen on project status day 2023?", 0.8),
    ("What is ARENA2036 welcoming new research directors?", 0.8),
    ("What is New collaboration on ARENA2036-X?", 0.8),
    ("What is ARENA2036 part of AI-Matters?", 0.8),
    ("What is ARENA2036 at the Productivity Symposium?", 0.8),

    # Additional Topics
    ("What is Circular Economy?", 0.8),
    ("What is Digital product development?", 0.8),
    ("What is Industrial Metaverse?", 0.8),
    ("What is Wire Harness?", 0.8),
    ("What is Quantum Technologies?", 0.8),
    ("What is Asset Administration Shell?", 0.8),
    ("What is data spaces?", 0.8),
    ("What are Deep Dives?", 0.8),
    ("What are Offers at ARENA2036?", 0.8),
    ("What is Cyber-physical production systems?", 0.8),
    ("What is Contao at arena2036.de?", 0.7),

    # Practical Information
    ("Where is the Venue for ARENA2036 events?", 0.8),
    ("How to get Tickets and registration for ARENA2036 events?", 0.8),
    ("What is the Call for Papers at ARENA2036?", 0.8),
    ("How to be an Exhibitor at ARENA2036?", 0.8),
    ("Where can I find the Agenda and program for ARENA2036 events?", 0.8),
    ("How to register for ARENA2036 newsletter?", 0.8),
    ("Where is the Sitemap for ARENA2036?", 0.7),
    ("Where can I find the Imprint for ARENA2036?", 0.7),
    ("Where is the Newsletter archive for ARENA2036?", 0.7),
    ("What was HMI 2023?", 0.8),
    ("Where is the News-Reader for ARENA2036?", 0.7),
    ("Where can I find all reports from ARENA2036?", 0.8),
    ("Where can I find all news from ARENA2036?", 0.8),
    ("What is the Project fair at ARENA2036?", 0.8),
    ("Where can I find Keynotes from ARENA2036?", 0.8),
    ("Where is the Photo gallery for ARENA2036?", 0.8),
    ("What was the Transfer Conference Nov' 2022?", 0.8),
    ("What was the Transfer conference May 2023?", 0.8),
    ("What was the AAS expert workshop Nov' 2023?", 0.8),
    ("What was the Transfer Conference Nov' 2023?", 0.8),
    ("What was the AAS expert workshop March 2024?", 0.8),
    ("What was the Transfer conference May 2024?", 0.8),
    ("What was the AAS expert workshop Sept' 2024?", 0.8),
    ("What was the Asset Administration Shell Hackathon Feb' 2025?", 0.8),
    ("What was the Asset Administration Shell Network Meeting Feb' 2025?", 0.8),
    ("What was the Kick-Off AAS Product Catalog Apr' 2025?", 0.8),
    ("What was the Asset Administration Shell Network Meeting Oct' 2025?", 0.8),
    ("Where can I find Events at ARENA2036?", 0.8),
    ("Where can I find Publications from ARENA2036?", 0.8),
    ("What was Results meeting Oct' 2024?", 0.8),
    ("What was Results meeting June 2025?", 0.8),
    ("What is Transfer and coordination at ARENA2036?", 0.8),
    ("What is Demonstrator for piloting and testing?", 0.8),
    ("What is Connection to Catena-X?", 0.8),
    ("What are Roles and rights in the Asset Administration Shell?", 0.8),
    ("What is Concept for automated negotiation processes?", 0.8),
    ("What is Concept for integrating the administration shells?", 0.8),
    ("What are Semantic principles for assembly in the car body?", 0.8),
    ("What are Tools for the application of VWS for production processes?", 0.8),
    ("What is Decentralized data management for the development process?", 0.8),
    ("What are Information models for the product description?", 0.8),
    ("What is POC for the implementation of change management with the AAS?", 0.8),
    ("What are Standards and middleware at ARENA2036?", 0.8),
    ("What is Integration of the Asset Administration Shell into the product catalog?", 0.8),
    ("What is Security POC for the use of AAS and EDC?", 0.8),
    ("Where can I find Results from ARENA2036 projects?", 0.8),
    ("What is Realization at ARENA2036?", 0.8),
    ("What is Project objective at ARENA2036?", 0.8),
    ("Who are Project partners at ARENA2036?", 0.8),
    ("What is Robotics Challenge at ARENA2036?", 0.8),
    ("Where can I find Events and newsletter at ARENA2036?", 0.8),
    ("What is Consortium at ARENA2036?", 0.8),
    ("What is Funding program and objectives at ARENA2036?", 0.8),
    ("How to Take part in the SILS?", 0.8),
    ("What is Standardization and extension of data profiles (SP7)?", 0.8),
    ("What is Extension of the standard to include high-frequency wiring harnesses (TP5)?", 0.8),
    ("What is Extension of the standard to include high-voltage wiring harnesses (TP4)?", 0.8),
    ("What is Optimization of automated connector assembly (TP2)?", 0.8),
    ("What is Automation-compatible Wire Harness (TP1)?", 0.8),
    ("What is DIN 72036 (TP0)?", 0.8),
    ("How to experience the 360° tour?", 0.8),
    ("How to Use added value at ARENA2036?", 0.8),
    ("How to Take part in ARENA2036 activities?", 0.8),
    ("Where can I find Dates and events at ARENA2036?", 0.8),
    ("Where can I find Reports from project meetings?", 0.8),
    ("Where can I find Announcements and events?", 0.8),
    ("Where can I find Publications and lectures?", 0.8),
    ("Where can I find Project partners and structure?", 0.8),
    ("What was Kick-off: February 07, 23?", 0.8),
    ("What was Milestone I: March 29, 2023?", 0.8),
    ("What was Milestone II: July 4, 2023?", 0.8),
    ("What was First Eclipse Tractus-X Community Days: December 7 + 8, 2023?", 0.8),
    ("What was data spaces theme day: February 08, 2024?", 0.8),
    ("What was Milestone III: March 13, 2024?", 0.8)
]



ENHANCED_SUGGESTIONS_DB_DE = [
    # Hauptbereiche
    ("Was ist ARENA2036?", 0.95),
    ("Was ist die Datenschutzrichtlinie bei ARENA2036?", 0.8),
    ("Wie kann ich mehr über das ARENA2036-Projekt erfahren?", 0.9),
    ("Wo finde ich den ARENA2036-Pressebereich?", 0.8),
    ("Was bietet ARENA2036 für mich?", 0.8),
    ("Was ist about:tomorrow bei ARENA2036?", 0.8),

    # Veranstaltungen
    ("Welche vergangenen Veranstaltungen hat ARENA2036 veranstaltet?", 0.85),
    ("Welche bevorstehenden Veranstaltungen gibt es bei ARENA2036?", 0.9),
    ("Was waren die Fifth Eclipse Tractus-X Community Days?", 0.8),
    ("Was ist die Women Of Tech Conference 25'?", 0.8),
    ("Was waren die Fourth Eclipse Tractus-X Community Days?", 0.8),
    ("Was war der Quantum-Day?", 0.8),
    ("Was waren die Third Eclipse Tractus-X Community Days?", 0.8),
    ("Was waren die Second Eclipse Tractus-X Community Days?", 0.8),
    ("Was war das SILS Forum: Präsentation der DIN 72036?", 0.8),
    ("Was war die Kick-off-Veranstaltung KIRR Real?", 0.8),
    ("Was ist die Hannover Messe 2025?", 0.8),
    ("Was ist 'the day after tomorrow - Open Research Campus'?", 0.8),
    ("Was war das Ergebnistreffen - AAS4WH?", 0.8),
    ("Was ist 'Open source in Manufacturing-X projects'?", 0.8),
    ("Was war der Catena-X Release Day?", 0.8),
    ("Was war der Themen-Tag 'KI / Robotik'?", 0.8),
    ("Was sind die Designrichtlinien für die Automatisierung des Kabelbaums?", 0.8),
    ("Was waren die First Eclipse Tractus-X Community Days?", 0.8),
    ("Was war die Einführung des Transformation Hub Wire Harness?", 0.8),
    ("Was war die Konferenzveranstaltung AAS4WH?", 0.8),
    ("Was waren die Projektstatustage im November 2019?", 0.8),
    ("Was war das Innovationsforum Wire Harness 2025?", 0.8),
    ("Was ist die WirePro Expo 2024?", 0.8),
    ("Was war das SynergyRegion Projektabschluss & Networking?", 0.8),
    ("Was war Manufacturing-X: Milestone Meeting III?", 0.8),
    ("Was war ARENA2036 - Rückblick auf das Jahr 2024?", 0.8),
    ("Ist DIN 72036 jetzt auf Englisch verfügbar?", 0.8),
    ("Was war der 'Intralogistik'-Thementag?", 0.8),
    ("Was war die Design Factory Stuttgart Sommergala 2023?", 0.8),
    ("Was ist THE Aerospace LÄND?", 0.8),
    ("Was war die Design Factory Stuttgart Wintergala 2023?", 0.8),
    ("Was war der DigiTain Projektstart?", 0.8),
    ("Was war die Design Factory Semesterabschlussgala am 23. Juni?", 0.8),
    ("Was war WHAT THE HECK? - Hackathon 2022?", 0.8),
    ("Was war der Additive 2022 Thementag?", 0.8),
    ("Was war die International Design Factory Week und DFGN.R Konferenz?", 0.8),
    ("Was war Robo Handling Wire Harness?", 0.8),
    ("Was war die Stuttgart Conference on Automotive Production 2022?", 0.8),
    ("Was war der Besuch von Wissenschaftsministerin Petra Olschowski?", 0.8),
    ("Was war der Besuch von Bundeswirtschaftsminister Peter Altmaier?", 0.8),
    ("Was war die Hannover Messe 2022?", 0.8),
    ("Was war der erste Jahrestag der Design Factory?", 0.8),
    ("Was war der Rückblick auf die Design Factory?", 0.8),
    ("Was war ARENA2036 auf der Hannover Messe 2025?", 0.8),
    ("Was war der Rückblick 2024?", 0.8),
    ("Was ist Ü:MO 2026?", 0.8),
    ("Was ist Ü:MO 2025 - über die Zukunft von morgen?", 0.8),
    ("Was war about:tomorrow 2024?", 0.8),
    ("Was ist Ü:MO 2025 - Partnertag auf dem Forschungscampus?", 0.8),
    ("Was war 22. Oktober 2024: Eröffnung Immersive Participation Lab Fraunhofer IAO?", 0.8),
    ("Was war 9. Januar 2025: Besuch des Siemens-Ausrüstungswerks in Erlangen?", 0.8),
    ("Was war 19. Februar 2025: Asset Administration Shell?", 0.8),
    ("Was war 25.-26. Februar: Industrial Metaverse Conference 2025?", 0.8),
    ("Was war 31. März - 4. April 2025: Hannover Messe 2025?", 0.8),
    ("Was war 8. Mai 2025: Virtuelle Welten - Chancen im Metaverse erleben?", 0.8),
    ("Was war 14. Mai Women Of Tech Conference 2025?", 0.8),
    ("Was war 26. Juni 2025: Ü:MO 2025 - Jahreskonferenz auf dem Forschungscampus?", 0.8),
    ("Was war 17. Juli 2025: Transformation Summit 2025?", 0.8),
    ("Was war 2. Oktober 2025: Virtueller Prozessdesign mit digitalen Zwillingen am Beispiel eines Robotersystems?", 0.8),
    ("Was war 30. Oktober 2025: Virtual Deep Dive: Digitaler Zwilling eines Gebäudes?", 0.8),

    # Projekte und Forschung
    ("Was ist die Asset Administration Shell?", 0.9),
    ("Was ist Industrial-AI?", 0.9),
    ("Was ist Wire Harness?", 0.9),
    ("Was sind die Forschungsschwerpunkte bei ARENA2036?", 0.9),
    ("Was ist der Mehrwert für ARENA2036-Mitglieder?", 0.8),
    ("Wer sind die Mitglieder von ARENA2036?", 0.8),
    ("Was ist der Transformations-Hub für den Kabelbaum?", 0.8),
    ("Was ist die Kabelbaum-Standardisierungsinitiative?", 0.8),
    ("Was ist der interaktive Bosch-Boden?", 0.8),
    ("Was ist das Industrial Metaverse?", 0.8),
    ("Was ist die Projektübersicht bei ARENA2036?", 0.8),
    ("Was ist Catena-X?", 0.8),
    ("Was ist Netzwerkinfrastruktur für Industrie 4.0?", 0.8),
    ("Was ist Connect4HCA?", 0.8),
    ("Was ist EcoFrame?", 0.8),
    ("Was ist CARpulse?", 0.8),
    ("Was ist Well-defined?", 0.8),
    ("Wo finde ich eine Übersicht der Projekte bei ARENA2036?", 0.8),
    ("Was ist die Projektstruktur bei ARENA2036?", 0.8),
    ("Was ist UpFilT?", 0.8),
    ("Was ist SynergyRegion?", 0.8),
    ("Was ist SDM4FZI?", 0.8),
    ("Was ist ProdUXion?", 0.8),
    ("Was ist PRIMA?", 0.8),
    ("Was ist PAIRS?", 0.8),
    ("Was ist InterSpiN?", 0.8),
    ("Was ist Wissenschaft und Unterstützung bei ARENA2036?", 0.8),
    ("Was sind Veranstaltungen des IILS?", 0.8),
    ("Was ist Nachhaltigkeit bei ARENA2036?", 0.8),
    ("Was ist End-to-End-Digitalisierung?", 0.8),
    ("Was ist digitale Produktbeschreibung?", 0.8),
    ("Was sind Logistikprozesse?", 0.8),
    ("Was ist die automatisierte Installation des Kabelbaums im Fahrzeug?", 0.8),
    ("Was sind Produktionsprozesse und Ressourcen?", 0.8),
    ("Was ist Automatisierung der Qualitätskontrolle?", 0.8),
    ("Was ist der Automatisierungsindex?", 0.8),
    ("Was sind Konzepte für Kabelbäume?", 0.8),
    ("Was sind Designregeln für Steckverbinder?", 0.8),
    ("Was sind Designregeln für die Automatisierung des Kabelbaums?", 0.8),
    ("Was ist die DIN-Norm?", 0.8),
    ("Was ist die Gründung des IILS?", 0.8),
    ("Was ist die Kabelbaum-Innovationsinitiative?", 0.8),
    ("Was ist IC4F?", 0.8),
    ("Was ist I4Production?", 0.8),
    ("Was ist GrantSLAM?", 0.8),
    ("Was ist EINST4INE?", 0.8),
    ("Was ist Torque?", 0.8),
    ("Was ist DIRECT?", 0.8),
    ("Was ist ein automatisiertes 3D-Drucksystem?", 0.8),
    ("Was ist das Team bei ARENA2036?", 0.8),
    ("Was ist CreatorBOX?", 0.8),
    ("Was sind ARENA2036 Face Shields?", 0.8),
    ("Was ist ANTS4.0?", 0.8),
    ("Was ist AIMM?", 0.8),
    ("Was ist Fluid Production?", 0.8),
    ("Was ist FlexCAR?", 0.8),
    ("Was ist digitaler Fingerabdruck?", 0.8),
    ("Was ist der Agile Innovation Hub?", 0.8),
    ("Was ist KHoch3?", 0.8),
    ("Was ist UX für die Produktion?", 0.8),
    ("Was ist LeiFu?", 0.8),
    ("Was ist ForschFab?", 0.8),
    ("Was ist DigitPro?", 0.8),
    ("Was sind allgemeine Informationen zu ARENA2036?", 0.8),
    ("Was ist 5G MIPS?", 0.8),
    ("Was ist Transfer-X?", 0.8),
    ("Was ist Robotic SEAM?", 0.8),
    ("Was ist Opti-feel?", 0.8),
    ("Was ist KIRR Real?", 0.8),
    ("Was ist KI-D @ ARENA2036-X?", 0.8),
    ("Was ist HyMatFlow?", 0.8),
    ("Was ist Holodeck?", 0.8),
    ("Was ist High Speed Sintering?", 0.8),
    ("Was ist ECOPOWERBRAKE?", 0.8),
    ("Was ist DigiAutoFab?", 0.8),
    ("Was ist die Design Factory Stuttgart?", 0.8),
    ("Was ist DARKO?", 0.8),
    ("Was ist Construct-X?", 0.8),
    ("Was ist CHEMampere?", 0.8),
    ("Was ist CeSaRa?", 0.8),
    ("Was ist CARS 2.0?", 0.8),
    ("Was ist AI-MATTERS?", 0.8),

    # Partner und Mitglieder
    ("Was ist OMRONs Mitgliedschaft bei ARENA2036?", 0.8),
    ("Was ist AMPLINKs Beitritt zu ARENA2036?", 0.8),
    ("Was ist die Zusammenarbeit von ARENA2036 mit acatech?", 0.8),
    ("Was ist das neue Mitglied SAFELOG?", 0.8),
    ("Was ist das neue Logo für ARENA2036?", 0.8),
    ("Was ist Bordnetze Digital 2024 in Stuttgart?", 0.8),
    ("Was ist das neue Mitglied QuiX Quantum?", 0.8),
    ("Was ist der neue Partner Hahn-Schickard?", 0.8),
    ("Was ist der neue Partner Schaeffler?", 0.8),
    ("Was ist der neue Partner InstaWerk?", 0.8),
    ("Was ist der neue Partner CIKONI?", 0.8),
    ("Was ist Agile Robots als Mitglied von ARENA2036?", 0.8),
    ("Was ist der erfolgreiche Eintritt von ARENA2036 in Phase III?", 0.8),
    ("Was ist das neue Mitglied Gründermotor?", 0.8),
    ("Was ist das neue acatech-Mitglied?", 0.8),
    ("Was ist das neue Mitglied Waveye?", 0.8),
    ("Was ist das neue Mitglied Precitec?", 0.8),
    ("Was ist DigiTain?", 0.8),
    ("Was ist die kartellrechtliche Genehmigung der Kooperation zur Automatisierung des Kabelbaums?", 0.8),
    ("Was war ARENA2036-Wasen beim Projektstatustag 2023?", 0.8),
    ("Was ist die Begrüßung neuer Forschungsleiter bei ARENA2036?", 0.8),
    ("Was ist die neue Zusammenarbeit zu ARENA2036-X?", 0.8),
    ("Was ist ARENA2036 als Teil von AI-Matters?", 0.8),
    ("Was war ARENA2036 auf dem Produktivitätssymposium?", 0.8),

    # Zusätzliche Themen
    ("Was ist Kreislaufwirtschaft?", 0.8),
    ("Was ist digitale Produktentwicklung?", 0.8),
    ("Was ist das Industrial Metaverse?", 0.8),
    ("Was ist ein Kabelbaum?", 0.8),
    ("Was sind Quantentechnologien?", 0.8),
    ("Was ist die Asset Administration Shell?", 0.8),
    ("Was sind Datenräume?", 0.8),
    ("Was sind Deep Dives?", 0.8),
    ("Was sind Angebote bei ARENA2036?", 0.8),
    ("Was sind cyber-physische Produktionssysteme?", 0.8),
    ("Was ist Contao auf arena2036.de?", 0.7),

    # Praktische Informationen
    ("Wo ist der Veranstaltungsort für ARENA2036-Events?", 0.8),
    ("Wie bekomme ich Tickets und registriere mich für ARENA2036-Veranstaltungen?", 0.8),
    ("Was ist der Call for Papers bei ARENA2036?", 0.8),
    ("Wie werde ich Aussteller bei ARENA2036?", 0.8),
    ("Wo finde ich die Agenda und das Programm für ARENA2036-Veranstaltungen?", 0.8),
    ("Wie registriere ich mich für den ARENA2036-Newsletter?", 0.8),
    ("Wo ist die Sitemap für ARENA2036?", 0.7),
    ("Wo finde ich das Impressum für ARENA2036?", 0.7),
    ("Wo ist das Newsletter-Archiv für ARENA2036?", 0.7),
    ("Was war die HMI 2023?", 0.8),
    ("Wo ist der News-Reader für ARENA2036?", 0.7),
    ("Wo finde ich alle Berichte von ARENA2036?", 0.8),
    ("Wo finde ich alle Nachrichten von ARENA2036?", 0.8),
    ("Was ist die Projektmesse bei ARENA2036?", 0.8),
    ("Wo finde ich Keynotes von ARENA2036?", 0.8),
    ("Wo ist die Fotogalerie für ARENA2036?", 0.8),
    ("Was war die Transferkonferenz November 2022?", 0.8),
    ("Was war die Transferkonferenz Mai 2023?", 0.8),
    ("Was war der AAS-Expertenworkshop November 2023?", 0.8),
    ("Was war die Transferkonferenz November 2023?", 0.8),
    ("Was war der AAS-Expertenworkshop März 2024?", 0.8),
    ("Was war die Transferkonferenz Mai 2024?", 0.8),
    ("Was war der AAS-Expertenworkshop September 2024?", 0.8),
    ("Was war der Asset Administration Shell Hackathon Februar 2025?", 0.8),
    ("Was war das Asset Administration Shell Netzwerktreffen Februar 2025?", 0.8),
    ("Was war der Kick-Off AAS Product Catalog April 2025?", 0.8),
    ("Was war das Asset Administration Shell Netzwerktreffen Oktober 2025?", 0.8),
    ("Wo finde ich Veranstaltungen bei ARENA2036?", 0.8),
    ("Wo finde ich Publikationen von ARENA2036?", 0.8),
    ("Was war das Ergebnistreffen Oktober 2024?", 0.8),
    ("Was war das Ergebnistreffen Juni 2025?", 0.8),
    ("Was ist Transfer und Koordination bei ARENA2036?", 0.8),
    ("Was ist der Demonstrator für Pilotierung und Tests?", 0.8),
    ("Was ist die Verbindung zu Catena-X?", 0.8),
    ("Was sind Rollen und Rechte in der Asset Administration Shell?", 0.8),
    ("Was ist das Konzept für automatisierte Verhandlungsprozesse?", 0.8),
    ("Was ist das Konzept für die Integration der Verwaltungsschalen?", 0.8),
    ("Was sind semantische Prinzipien für die Montage in der Karosserie?", 0.8),
    ("Was sind Tools für die Anwendung von VWS für Produktionsprozesse?", 0.8),
    ("Was ist dezentrales Datenmanagement für den Entwicklungsprozess?", 0.8),
    ("Was sind Informationsmodelle für die Produktbeschreibung?", 0.8),
    ("Was ist der POC für die Implementierung des Änderungsmanagements mit der AAS?", 0.8),
    ("Was sind Standards und Middleware bei ARENA2036?", 0.8),
    ("Was ist die Integration der Asset Administration Shell in den Produktkatalog?", 0.8),
    ("Was ist der Security POC für die Nutzung von AAS und EDC?", 0.8),
    ("Wo finde ich Ergebnisse aus ARENA2036-Projekten?", 0.8),
    ("Was ist Realisierung bei ARENA2036?", 0.8),
    ("Was ist das Projektziel bei ARENA2036?", 0.8),
    ("Wer sind die Projektpartner bei ARENA2036?", 0.8),
    ("Was ist die Robotics Challenge bei ARENA2036?", 0.8),
    ("Wo finde ich Veranstaltungen und Newsletter bei ARENA2036?", 0.8),
    ("Was ist das Konsortium bei ARENA2036?", 0.8),
    ("Was ist das Förderprogramm und die Ziele bei ARENA2036?", 0.8),
    ("Wie kann ich am SILS teilnehmen?", 0.8),
    ("Was ist die Standardisierung und Erweiterung von Datenprofilen (SP7)?", 0.8),
    ("Was ist die Erweiterung des Standards um Hochfrequenz-Kabelbäume (TP5)?", 0.8),
    ("Was ist die Erweiterung des Standards um Hochspannungs-Kabelbäume (TP4)?", 0.8),
    ("Was ist die Optimierung der automatisierten Steckverbinder-Montage (TP2)?", 0.8),
    ("Was ist der automatisierungskompatible Kabelbaum (TP1)?", 0.8),
    ("Was ist DIN 72036 (TP0)?", 0.8),
    ("Wie kann ich die 360°-Tour erleben?", 0.8),
    ("Wie nutze ich den Mehrwert bei ARENA2036?", 0.8),
    ("Wie kann ich an ARENA2036-Aktivitäten teilnehmen?", 0.8),
    ("Wo finde ich Termine und Veranstaltungen bei ARENA2036?", 0.8),
    ("Wo finde ich Berichte von Projekttreffen?", 0.8),
    ("Wo finde ich Ankündigungen und Veranstaltungen?", 0.8),
    ("Wo finde ich Publikationen und Vorträge?", 0.8),
    ("Wo finde ich Projektpartner und Strukturen?", 0.8),
    ("Was war der Kick-off: 07. Februar 23?", 0.8),
    ("Was war Meilenstein I: 29. März 2023?", 0.8),
    ("Was war Meilenstein II: 4. Juli 2023?", 0.8),
    ("Was waren die First Eclipse Tractus-X Community Days: 7. + 8. Dezember 2023?", 0.8),
    ("Was war der Datenräume-Thementag: 8. Februar 2024?", 0.8),
    ("Was war Meilenstein III: 13. März 2024?", 0.8)
]